---
language: ruby
sudo: false
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: fpHEeFa7O3qiD/omNMDUH9Pt4wrlnuw9DjhgfPU6uYgHCzRcrd0B5mj+mxPSNLlnTV6tf3IV/PIlDVxzxiy6QY6NcKtHdX7Olieue6pCEodR0GumCheEvXyOptVyl+eiHrVJYavOtKwiJEKd2m3xo/DL2gdlHTBJtWpLz5Zb7NADHfo+QFvZXoXDMo1U0psLeoVhgSAODUrX3ri04yRG1Jt7OAOSb/P6ThpRQD1bT9PPo6yN4NRvNAy/rjcidXj2V+UOAkY3Cs0MbxDuPW9Ga6UfK4ciZ7y8CsgvwFzOC18Tjk+Q/unGRW8VJ2hqA78i/C/pMzB1DkmESHfGObfavUkG4s4+FjTaLHjSIVCvWTlpMA16ZZGxMKy0asvCg3P2M41cgxQl/znDDMeSOEv2yUiQ+tw74DAfkGKCylOd1ojcRYrOz9ZNyhWLkXDwLBhc/fyEPlA2A7q4Iw5u2TE/jitXaVtF2fXcCd91M9VuoB18wu4Sg0+7DYoSotlDkmJPpt4Ie9EYiAmW4YM2sBtZTFAqDC+H5PDLIcIvnb3FsvOE2bntLOP1SLMa8YOXMAqOeGN4dcB/MwZWhjnaZa2v1+ZAvlVuJ2A0GD6YqNO976Tqtkj27uAvZL3oSUwvjYFXuNscS6SUrJvBeZiof9hi1MB7kq7giPmo9oDfNHfjHp0=
  gem: puppet-lint-anchor-check
  on:
    tags: true
    repo: voxpupuli/puppet-lint-anchor-check
